/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vistas;

import Controles.UsuariosDAO;
import Objetos.Usuario;
import Recurso.Conexion;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author ACER
 */
public class Panel extends javax.swing.JPanel {

        private UsuariosDAO usuariosDAO;
    
    
    /**
     * Creates new form PanelDEinformacion
     */
    public Panel() {
        this.usuariosDAO = usuariosDAO; // Inicializa el DAO
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        BOTONAGREGAR = new javax.swing.JButton();
        BOTONusuarios = new javax.swing.JButton();
        BOTONinventario = new javax.swing.JButton();
        BOTONMaquinas = new javax.swing.JButton();
        BOTONMateriales = new javax.swing.JButton();
        BOTONInformes = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setPreferredSize(new java.awt.Dimension(1080, 750));

        jInternalFrame1.setVisible(true);

        BOTONAGREGAR.setText("Salir");
        BOTONAGREGAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOTONAGREGARMouseClicked(evt);
            }
        });
        BOTONAGREGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONAGREGARActionPerformed(evt);
            }
        });

        BOTONusuarios.setText("Usuarios");
        BOTONusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOTONusuariosMouseClicked(evt);
            }
        });
        BOTONusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONusuariosActionPerformed(evt);
            }
        });

        BOTONinventario.setText("Inventario");
        BOTONinventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOTONinventarioMouseClicked(evt);
            }
        });
        BOTONinventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONinventarioActionPerformed(evt);
            }
        });

        BOTONMaquinas.setText("Maquinas");
        BOTONMaquinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOTONMaquinasMouseClicked(evt);
            }
        });
        BOTONMaquinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONMaquinasActionPerformed(evt);
            }
        });

        BOTONMateriales.setText("Materiales");
        BOTONMateriales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOTONMaterialesMouseClicked(evt);
            }
        });
        BOTONMateriales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONMaterialesActionPerformed(evt);
            }
        });

        BOTONInformes.setText("Informes");
        BOTONInformes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BOTONInformesMouseClicked(evt);
            }
        });
        BOTONInformes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONInformesActionPerformed(evt);
            }
        });

        jMenu3.setText("File");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar1.add(jMenu4);

        jInternalFrame1.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(871, Short.MAX_VALUE)
                .addComponent(BOTONAGREGAR, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BOTONusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOTONinventario, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOTONMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOTONMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BOTONInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BOTONusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BOTONinventario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BOTONMaquinas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BOTONMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BOTONInformes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 328, Short.MAX_VALUE)
                .addComponent(BOTONAGREGAR)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BOTONAGREGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONAGREGARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOTONAGREGARActionPerformed

    private void BOTONAGREGARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOTONAGREGARMouseClicked
        
        try {
        // Obtener la conexión a la base de datos
        Connection connection = Conexion.getConnection();
        
        // Crear una instancia de UsuariosDAO con la conexión
        UsuariosDAO usuariosDAO = new UsuariosDAO(connection);
        
        // Crear un nuevo objeto Usuario con valores manuales
        Usuario nuevoUsuario = new Usuario(
            0,  // El ID no es necesario porque es autoincremental en la base de datos
            "Juan", // Primer nombre
            "Carlos", // Segundo nombre
            "Pérez", // Apellido paterno
            "López", // Apellido materno
            "555-1234", // Teléfono personal
            "555-5678", // Teléfono de emergencia
            "Maestro", // Rol (Peón, Oficial, Maestro, etc.)
            "Capacitado", // Estado de capacitación (Capacitado, No capacitado)
            "juan.perez@example.com", // Email
            "contrasena123" // Contraseña
        );
        
        // Guardar el nuevo usuario en la base de datos
        usuariosDAO.addUsuario(nuevoUsuario);
        
        JOptionPane.showMessageDialog(this, "Usuario agregado exitosamente");
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al agregar el usuario: " + e.getMessage());
    }
        
        
    }//GEN-LAST:event_BOTONAGREGARMouseClicked

    private void BOTONusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOTONusuariosMouseClicked
        // Credenciales correctas, abrir el siguiente panel
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            System.out.println("Bandera 5");
            frame.setSize(1500, 810);
            //frame.setContentPane(new Maquinas()); // Cambiar al nuevo panel
            frame.setContentPane(new Usuarios()); // Cambiar al nuevo panel
            //frame.setContentPane(new Materiales()); // Cambiar al nuevo panel
            System.out.println("Bandera 5");
            frame.revalidate(); // Actualizar la interfaz
    }//GEN-LAST:event_BOTONusuariosMouseClicked

    private void BOTONusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONusuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOTONusuariosActionPerformed

    private void BOTONinventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOTONinventarioMouseClicked
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            System.out.println("Bandera 5");
            frame.setSize(1500, 810);
            //frame.setContentPane(new Maquinas()); // Cambiar al nuevo panel
            //frame.setContentPane(new Usuarios()); // Cambiar al nuevo panel
            //frame.setContentPane(new Materiales()); // Cambiar al nuevo panel
            frame.setContentPane(new Inventario()); // Cambiar al nuevo panel
            System.out.println("Bandera 5");
            frame.revalidate(); // Actualizar la interfaz
    }//GEN-LAST:event_BOTONinventarioMouseClicked

    private void BOTONinventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONinventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOTONinventarioActionPerformed

    private void BOTONMaquinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOTONMaquinasMouseClicked
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            System.out.println("Bandera 5");
            frame.setSize(1500, 810);
            frame.setContentPane(new Maquinas()); // Cambiar al nuevo panel
            //frame.setContentPane(new Usuarios()); // Cambiar al nuevo panel
            //frame.setContentPane(new Materiales()); // Cambiar al nuevo panel
            //frame.setContentPane(new Inventario()); // Cambiar al nuevo panel
            System.out.println("Bandera 5");
            frame.revalidate(); // Actualizar la interfaz
    }//GEN-LAST:event_BOTONMaquinasMouseClicked

    private void BOTONMaquinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONMaquinasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOTONMaquinasActionPerformed

    private void BOTONMaterialesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOTONMaterialesMouseClicked
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            System.out.println("Bandera 5");
            frame.setSize(1500, 810);
            //frame.setContentPane(new Maquinas()); // Cambiar al nuevo panel
            //frame.setContentPane(new Usuarios()); // Cambiar al nuevo panel
            frame.setContentPane(new Materiales()); // Cambiar al nuevo panel
            //frame.setContentPane(new Inventario()); // Cambiar al nuevo panel
            System.out.println("Bandera 5");
            frame.revalidate(); // Actualizar la interfaz
    }//GEN-LAST:event_BOTONMaterialesMouseClicked

    private void BOTONMaterialesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONMaterialesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOTONMaterialesActionPerformed

    private void BOTONInformesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BOTONInformesMouseClicked
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            System.out.println("Bandera 5");
            frame.setSize(1500, 810);
            //frame.setContentPane(new Maquinas()); // Cambiar al nuevo panel
            //frame.setContentPane(new Usuarios()); // Cambiar al nuevo panel
            frame.setContentPane(new Informes()); // Cambiar al nuevo panel
            //frame.setContentPane(new Inventario()); // Cambiar al nuevo panel
            System.out.println("Bandera 5");
            frame.revalidate(); // Actualizar la interfaz
    }//GEN-LAST:event_BOTONInformesMouseClicked

    private void BOTONInformesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONInformesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BOTONInformesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTONAGREGAR;
    private javax.swing.JButton BOTONInformes;
    private javax.swing.JButton BOTONMaquinas;
    private javax.swing.JButton BOTONMateriales;
    private javax.swing.JButton BOTONinventario;
    private javax.swing.JButton BOTONusuarios;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
